version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - generator
    environment:
      - MODEL_PATH=/app/model/GRU.pth
    volumes:
      - ./backend/data:/app/data
      - ./backend/model:/app/model
      - ./backend/app:/app/app

  generator:
    build: ./generator
    ports:
      - "5001:5000"
    environment:
      - API_URL=http://backend:8000
    volumes:
      - ./generator:/app
